### ISSUE TITLE
Where do I get the cracolessResourcesLoader

### ISSUE THREAD

**Issue by chenxubin2016** [condorheroblog/craco-plugin-style-resources-loader#1]
const cracoPluginStyleResourcesLoader = require('craco-plugin-style-resources-loader');
const path = require('path');
 
module.exports = {
    plugin: cracoLessResourcesLoader,
    options: {
        patterns: [
            path.join(__dirname, 'src/less/common.less'),
            path.join(__dirname, 'src/less/global.less')
        ],
        /* 
            Please enter supported CSS processor type
            1. if u use css processor，please type css string
            2. if u use less processor，please type less string
            3. if u use sass or scss processor，please type sass or scss string，Choose one of the two
            4. if u use stylus processor，please type stylus string
        */
        styleType: 'less'
    }
};

Where is the cracoPluginStyleResourcesLoader used?
Where does the cracolessResourcesLoader come from

**Comment by condorheroblog** [comment]
![image](https://user-images.githubusercontent.com/47056890/112442041-5c621d00-8d86-11eb-9f42-ac4325b6595d.png)
